import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  aclSidebar: [{ type: 'autogenerated', dirName: 'egose-acl' }],
  adapterjsSidebar: [{ type: 'autogenerated', dirName: 'egose-adapter-js' }],
  swaggerSidebar: [{ type: 'autogenerated', dirName: 'egose-swagger' }],
  decoSidebar: [{ type: 'autogenerated', dirName: 'egose-deco' }],
};

export default sidebars;
