repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-added-large-files
  - id: check-executables-have-shebangs
    files: \.sh
  - id: check-json
  - id: check-vcs-permalinks
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-merge-conflict
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: a362181620503bf7446d3f5c98cc004b9403543d
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
- repo: local
  hooks:
  - id: eslint-prettier
    name: Lint and Style
    language: system
    files: \.(j|t)s$
    entry: bash -c 'yarn format && yarn lint'
    pass_filenames: false
