name: Setup Tools
description: Setup required tools in the workspace

runs:
  using: composite
  steps:
  - name: Setup Tools
    uses: egose/actions/asdf-tools@73f4988ba414d27e94f2d6e97d9b10f77a5128cd
    with:
      plugins: |
        mongodb=https://github.com/junminahn/asdf-mongodb.git

  - name: Install additional asdf packages
    run: |
      asdf install mongodb 4.4.8
      asdf install mongodb 5.3.2
      asdf install mongodb 6.0.11
    shell: bash

  - name: Install python tools
    run: |
      pip3 install --upgrade pip
      pip install -r requirements.txt
      asdf reshim
    shell: bash
