name: Setup Tools
description: Setup required tools in the workspace

runs:
  using: composite
  steps:
  - name: Setup Tools
    uses: egose/actions/asdf-tools@c039a6e6f6b82da0f446302dd9582f4c6f663cb7
    with:
      plugins: |
        mongodb=https://github.com/junminahn/asdf-mongodb.git

  - name: Install additional asdf packages
    run: |
      asdf install mongodb 4.4.8
      asdf install mongodb 5.3.2
      asdf install mongodb 6.0.11
    shell: bash

  - name: Install python tools
    run: |
      pip3 install --upgrade pip
      pip install -r requirements.txt
      asdf reshim
    shell: bash
