name: Publish Docusaurus via GitHub Pages

on:
  push:
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: hmarr/debug-action@f7318c783045ac39ed9bb497e22ce835fdafbfe6
    - uses: actions/checkout@cbb722410c2e876e24abbe8de2cc27693e501dcb

    - name: Setup Tools
      uses: ./.github/actions/setup-tools

    - name: Setup NPM Packages
      uses: ./.github/actions/setup-yarn

    - name: Build the Docusaurus site
      run: |
        yarn build
      working-directory: docusaurus

    - name: Deploy GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3c4f14a9dd16589e133efef395ad4f3e79d1f277
      with:
        repository-name: egose/egose.github.io
        branch: gh-pages
        folder: ./docusaurus/build
        ssh-key: ${{ secrets.DEPLOY_KEY }}
