name: Publish Docusaurus via GitHub Pages

on:
  push:
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: hmarr/debug-action@f7318c783045ac39ed9bb497e22ce835fdafbfe6
    - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2

    - name: Setup Tools
      uses: ./.github/actions/setup-tools

    - name: Setup NPM Packages
      uses: ./.github/actions/setup-yarn

    - name: Build the Docusaurus site
      run: |
        yarn build
      working-directory: docusaurus

    - name: Deploy GitHub Pages
      uses: JamesIves/github-pages-deploy-action@deb5e359578fea0f6d84eb6e48886999311e181f
      with:
        repository-name: egose/egose.github.io
        branch: gh-pages
        folder: ./docusaurus/build
        ssh-key: ${{ secrets.DEPLOY_KEY }}
