name: Publish MkDocs via GitHub Pages

on:
  push:
    branches:
    - _main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: hmarr/debug-action@f7318c783045ac39ed9bb497e22ce835fdafbfe6
    - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2

    - name: Setup Tools
      uses: ./.github/actions/setup-tools

    - name: Build the MkDocs site
      run: |
        make mk-build

    - name: Deploy GitHub Pages
      uses: JamesIves/github-pages-deploy-action@f9cbe5cd0b5c7a4809e6a86ea38fa319da375a03
      with:
        repository-name: egose/egose.github.io
        branch: gh-pages
        folder: ./site
        ssh-key: ${{ secrets.DEPLOY_KEY }}
