name: Publish docs via GitHub Pages

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: hmarr/debug-action@v2
    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

    - name: Setup Tools
      uses: ./.github/actions/setup-tools

    - name: Build the MkDocs site
      run: |
        make mk-build

    - name: Deploy GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        repository-name: egose/egose.github.io
        branch: gh-pages
        folder: ./site
        ssh-key: ${{ secrets.DEPLOY_KEY }}
