name: Publish NPM Packages

on:
  push:
    tags:
    - v*.*.*

jobs:
  build-and-publish:
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
    - uses: hmarr/debug-action@f7318c783045ac39ed9bb497e22ce835fdafbfe6
    - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2

    - name: Setup Tools
      uses: ./.github/actions/setup-tools

    - name: Setup NPM Packages
      uses: ./.github/actions/setup-yarn

    - name: Publish Packages
      run: |
        cat >"/home/runner/.npmrc" <<EOF
        //registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}
        registry=https://registry.npmjs.org/
        always-auth=true
        EOF
        node scripts/publish-all --tag=${{github.ref_name}}
