name: Tests
on:
  push

jobs:
  tests-pre-commit:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: hmarr/debug-action@v2
      - uses: actions/checkout@v3

      - name: Setup Tools
        uses: ./.github/actions/setup-tools

      - name: Setup NPM Packages
        uses: ./.github/actions/setup-yarn

      - name: Start mongod as a Daemon
        run: |
          mkdir -p ~/mongo/data/db
          mongod --fork --dbpath ~/mongo/data/db --logpath ~/mongo/mongod.log

      - name: Run unit tests
        run: yarn test

      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Rerun Pre-Commit Hooks on CI
        run: |
          pip install -r requirements.txt
          pre-commit run --all-files

  commitlint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v2
