name: Tests
on: push

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        express: [4.6.0, latest]
        mongoose: [5.2.0, 6.0.15, 6.10.5, latest]
    steps:
    - uses: hmarr/debug-action@v2
    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

    - name: Setup Tools
      uses: ./.github/actions/setup-tools

    - name: Setup NPM Packages
      uses: ./.github/actions/setup-yarn

    - name: Install target package versions
      run: |
        yarn upgrade express@${{ matrix.express }} --dev
        yarn upgrade mongoose@${{ matrix.mongoose }} --dev

    - name: Start mongod as a Daemon
      run: |
        mkdir -p ~/mongo/data/db
        mongod --fork --dbpath ~/mongo/data/db --logpath ~/mongo/mongod.log

    - name: Run unit tests
      run: yarn test

  pre-commit:
    runs-on: ubuntu-22.04
    steps:
    - uses: hmarr/debug-action@v2
    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

    - name: Setup Tools
      uses: ./.github/actions/setup-tools

    - name: Setup NPM Packages
      uses: ./.github/actions/setup-yarn

    - uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - name: Rerun Pre-Commit Hooks on CI
      run: |
        pip install -r requirements.txt
        pre-commit run --all-files

  commitlint:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      with:
        fetch-depth: 0
    - uses: wagoid/commitlint-github-action@v5
