name: Tests

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        express: [4.6.0, latest]
        # See https://mongoosejs.com/docs/compatibility.html
        # <mongodb-ver>_<mongoose-ver>
        mongoose: [4.4.8_5.2.0, 5.3.2_6.0.15, 6.0.11_6.10.5, 6.0.11_latest]
    steps:
    - uses: hmarr/debug-action@v2
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4

    - name: Setup Tools
      uses: ./.github/actions/setup-tools

    - name: Setup NPM Packages
      uses: ./.github/actions/setup-yarn

    - name: Install target package versions
      run: |
        IFS="_"
        read -ra parts <<< ${{ matrix.mongoose }}
        asdf local mongodb ${parts[0]}
        yarn upgrade express@${{ matrix.express }} --dev
        yarn upgrade mongoose@${parts[1]} --dev

    - name: Start mongod as a Daemon
      run: |
        mkdir -p ~/mongo/data/db
        mongod --fork --dbpath ~/mongo/data/db --logpath ~/mongo/mongod.log

    - name: Run unit tests
      run: yarn test

  pre-commit:
    runs-on: ubuntu-22.04
    steps:
    - uses: hmarr/debug-action@v2
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4

    - name: Setup Tools
      uses: ./.github/actions/setup-tools

    - name: Setup NPM Packages
      uses: ./.github/actions/setup-yarn

    - uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - name: Rerun Pre-Commit Hooks on CI
      run: |
        pip install -r requirements.txt
        pre-commit run --all-files

  commitlint:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      with:
        fetch-depth: 0
    - uses: wagoid/commitlint-github-action@v6
