name: Setup NPM Packages
description: Setup required nodejs packages in the workspace

runs:
  using: composite
  steps:
  - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684
    with:
      path: |
        **/node_modules
      key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

  - name: Install Yarn dependencies
    run: |
      yarn
    shell: bash

  - name: Install Yarn dependencies
    run: |
      yarn
    working-directory: docusaurus
    shell: bash
