name: Setup NPM Packages
description: Setup required nodejs packages in the workspace

runs:
  using: composite
  steps:
  - uses: actions/cache@36f1e144e1c8edb0a652766b484448563d8baf46
    with:
      path: |
        **/node_modules
      key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

  - name: Install Yarn dependencies
    run: |
      yarn
    shell: bash

  - name: Install Yarn dependencies
    run: |
      yarn
    working-directory: docusaurus
    shell: bash
