name: Setup NPM Packages
description: Setup required nodejs packages in the workspace

runs:
  using: composite
  steps:
  - uses: actions/cache@9fa7e61ec7e1f44ac75218e7aaea81da8856fd11
    with:
      path: |
        **/node_modules
      key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

  - name: Install Yarn dependencies
    run: |
      yarn
    shell: bash

  - name: Install Yarn dependencies
    run: |
      yarn
    working-directory: docusaurus
    shell: bash
